#line 1 "babyc_lex.flex.c"

#line 3 "babyc_lex.flex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer bb_create_buffer
#define yy_delete_buffer bb_delete_buffer
#define yy_scan_buffer bb_scan_buffer
#define yy_scan_string bb_scan_string
#define yy_scan_bytes bb_scan_bytes
#define yy_init_buffer bb_init_buffer
#define yy_flush_buffer bb_flush_buffer
#define yy_load_buffer_state bb_load_buffer_state
#define yy_switch_to_buffer bb_switch_to_buffer
#define yypush_buffer_state bbpush_buffer_state
#define yypop_buffer_state bbpop_buffer_state
#define yyensure_buffer_stack bbensure_buffer_stack
#define yy_flex_debug bb_flex_debug
#define yyin bbin
#define yyleng bbleng
#define yylex bblex
#define yylineno bblineno
#define yyout bbout
#define yyrestart bbrestart
#define yytext bbtext
#define yywrap bbwrap
#define yyalloc bballoc
#define yyrealloc bbrealloc
#define yyfree bbfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define bb_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer bb_create_buffer
#endif

#ifdef yy_delete_buffer
#define bb_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer bb_delete_buffer
#endif

#ifdef yy_scan_buffer
#define bb_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer bb_scan_buffer
#endif

#ifdef yy_scan_string
#define bb_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string bb_scan_string
#endif

#ifdef yy_scan_bytes
#define bb_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes bb_scan_bytes
#endif

#ifdef yy_init_buffer
#define bb_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer bb_init_buffer
#endif

#ifdef yy_flush_buffer
#define bb_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer bb_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define bb_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state bb_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define bb_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer bb_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define bbpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state bbpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define bbpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state bbpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define bbensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack bbensure_buffer_stack
#endif

#ifdef yylex
#define bblex_ALREADY_DEFINED
#else
#define yylex bblex
#endif

#ifdef yyrestart
#define bbrestart_ALREADY_DEFINED
#else
#define yyrestart bbrestart
#endif

#ifdef yylex_init
#define bblex_init_ALREADY_DEFINED
#else
#define yylex_init bblex_init
#endif

#ifdef yylex_init_extra
#define bblex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra bblex_init_extra
#endif

#ifdef yylex_destroy
#define bblex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy bblex_destroy
#endif

#ifdef yyget_debug
#define bbget_debug_ALREADY_DEFINED
#else
#define yyget_debug bbget_debug
#endif

#ifdef yyset_debug
#define bbset_debug_ALREADY_DEFINED
#else
#define yyset_debug bbset_debug
#endif

#ifdef yyget_extra
#define bbget_extra_ALREADY_DEFINED
#else
#define yyget_extra bbget_extra
#endif

#ifdef yyset_extra
#define bbset_extra_ALREADY_DEFINED
#else
#define yyset_extra bbset_extra
#endif

#ifdef yyget_in
#define bbget_in_ALREADY_DEFINED
#else
#define yyget_in bbget_in
#endif

#ifdef yyset_in
#define bbset_in_ALREADY_DEFINED
#else
#define yyset_in bbset_in
#endif

#ifdef yyget_out
#define bbget_out_ALREADY_DEFINED
#else
#define yyget_out bbget_out
#endif

#ifdef yyset_out
#define bbset_out_ALREADY_DEFINED
#else
#define yyset_out bbset_out
#endif

#ifdef yyget_leng
#define bbget_leng_ALREADY_DEFINED
#else
#define yyget_leng bbget_leng
#endif

#ifdef yyget_text
#define bbget_text_ALREADY_DEFINED
#else
#define yyget_text bbget_text
#endif

#ifdef yyget_lineno
#define bbget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno bbget_lineno
#endif

#ifdef yyset_lineno
#define bbset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno bbset_lineno
#endif

#ifdef yywrap
#define bbwrap_ALREADY_DEFINED
#else
#define yywrap bbwrap
#endif

#ifdef yyalloc
#define bballoc_ALREADY_DEFINED
#else
#define yyalloc bballoc
#endif

#ifdef yyrealloc
#define bbrealloc_ALREADY_DEFINED
#else
#define yyrealloc bbrealloc
#endif

#ifdef yyfree
#define bbfree_ALREADY_DEFINED
#else
#define yyfree bbfree
#endif

#ifdef yytext
#define bbtext_ALREADY_DEFINED
#else
#define yytext bbtext
#endif

#ifdef yyleng
#define bbleng_ALREADY_DEFINED
#else
#define yyleng bbleng
#endif

#ifdef yyin
#define bbin_ALREADY_DEFINED
#else
#define yyin bbin
#endif

#ifdef yyout
#define bbout_ALREADY_DEFINED
#else
#define yyout bbout
#endif

#ifdef yy_flex_debug
#define bb_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug bb_flex_debug
#endif

#ifdef yylineno
#define bblineno_ALREADY_DEFINED
#else
#define yylineno bblineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define bbwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[199] =
    {   0,
        0,    0,    9,    9,    0,    0,   84,   82,   13,   14,
       42,   82,   47,   49,   82,   37,   38,   45,   43,   55,
       44,   46,   59,   57,   56,   54,   51,   53,   52,   81,
       39,   40,   50,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   35,   48,   36,   41,    5,    9,
       10,   83,   83,    2,   83,    4,   13,   34,    0,    6,
        0,   19,   28,   21,    0,    0,   17,   25,   15,   26,
       16,    8,    7,   18,   59,    0,   59,   59,   57,   57,
       57,   30,   32,   33,   31,   29,   81,   80,   22,   81,
       81,   81,   81,   81,   66,   81,   81,   81,   81,   81,

       81,   81,   81,   81,   20,   27,    5,    5,    9,   11,
       10,   12,    2,    3,   62,    0,    0,    0,    0,    0,
        7,   58,   59,   59,   57,   57,   24,   23,   81,   81,
       81,   81,   81,   78,   81,   81,   81,   81,   81,   81,
       81,   81,   81,    5,   61,   63,   64,   65,    0,   58,
       58,   78,   81,   81,   67,   68,   81,   81,   81,   81,
       81,   81,   81,   81,   75,   81,    5,   60,   58,   58,
       70,   81,   81,   81,   81,   81,   81,   81,   81,   69,
        5,   81,   79,   81,   73,   77,   72,   74,   81,    5,
       81,   81,   81,    5,   71,   76,    1,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   23,   22,   23,   24,   25,   26,   27,   28,
       29,   30,    9,    9,   31,   31,   31,   31,   31,   31,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   33,   32,   32,
       34,   35,   36,   37,   38,    9,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   48,   49,   50,   48,   51,
       52,   53,   48,   54,   55,   56,   57,   58,   59,   60,
       48,   61,   62,   63,   64,   65,    9,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    4,    3,    3,    3,    5,    3,
        6,    6,    6,    6,    6,    7,    3,    3,    3,    3,
        8,    9,    9,    3,    3,    3,    3,   10,    6,    6,
        6,    6,    6,    6,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,    3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[211] =
    {   0,
        0,  426,   63,   64,   66,   67,  433,  435,   71,  435,
      403,   63,  402,   63,  395,  435,  435,  400,   61,  435,
       62,   73,   78,   60,  435,  435,   58,  399,   74,  401,
      435,  435,  397,   79,   63,   80,   82,   81,   87,   83,
       90,   93,   95,   96,  435,   85,  435,  435,  378,    0,
      435,  109,  435,  118,    0,  435,  147,  435,  120,  435,
      421,  435,  435,  435,  411,  138,  435,  435,  435,  435,
      435,  435,    0,  435,  143,    0,  372,  371,  146,  370,
      369,  389,  435,  435,  435,  388,  390,  435,  435,  110,
       98,   92,  119,  127,  389,  128,  130,  131,  146,  137,

      151,  149,  132,  152,  435,  435,    0,  362,    0,  435,
      435,  435,  180,    0,  435,  189,  398,  395,  384,    0,
        0,  123,  435,  342,  435,  341,  435,  435,  164,  169,
      160,  162,  171,  191,  180,  183,  192,  193,  194,  195,
      198,  196,  202,  349,  435,  435,  435,  435,  357,  317,
      306,  279,  200,  201,  278,  276,  208,  203,  207,  211,
      205,  209,  236,  221,  275,  227,  250,  435,  435,  249,
      272,  213,  215,  229,  216,  237,  242,  239,  243,  271,
      239,  246,  269,  247,  264,  263,  262,  261,  248,  242,
      249,  250,  251,  239,  255,  252,    0,  435,  306,  317,

      328,  337,  343,  354,  365,  376,  383,  394,  400,  403
    } ;

static const flex_int16_t yy_def[211] =
    {   0,
      198,    1,  199,  199,  200,  200,  198,  198,  198,  198,
      198,  201,  198,  198,  202,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  203,
      198,  198,  198,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  198,  198,  198,  198,  204,  205,
      198,  206,  198,  198,  207,  198,  198,  198,  201,  198,
      201,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  208,  198,  198,  209,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  203,  198,  198,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,

      203,  203,  203,  203,  198,  198,  204,  204,  205,  198,
      198,  198,  198,  207,  198,  198,  198,  198,  198,  210,
      208,  209,  198,  198,  198,  198,  198,  198,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  204,  198,  198,  198,  198,  210,  198,
      198,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  204,  198,  198,  198,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      204,  203,  203,  203,  203,  203,  203,  203,  203,  204,
      203,  203,  203,  204,  203,  203,  204,    0,  198,  198,

      198,  198,  198,  198,  198,  198,  198,  198,  198,  198
    } ;

static const flex_int16_t yy_nxt[501] =
    {   0,
        8,    9,   10,    9,    9,   11,   12,    8,    8,   13,
       14,   15,   16,   17,   18,   19,   20,   21,    8,   22,
       23,   24,   24,   24,   24,   25,   26,   27,   28,   29,
       30,   30,   30,   31,    8,   32,   33,   30,   30,   34,
       35,   30,   36,   30,   37,   30,   38,   30,   30,   39,
       30,   30,   30,   40,   41,   30,   42,   43,   44,   30,
       30,   45,   46,   47,   48,   51,   51,   54,   54,   60,
       54,   54,   57,   63,   57,   57,   68,   52,   52,   70,
       79,   79,   79,   79,   79,   82,   83,   72,   88,   69,
       71,   64,   73,   55,   55,   56,   56,   61,   75,   75,

       75,   74,   85,   86,   88,   88,   88,   88,   88,   80,
       76,  111,   88,  105,   92,   88,   81,   88,   88,  113,
       88,   88,  113,   88,   95,   98,   60,   77,  112,   93,
       90,   96,   91,   94,   78,   88,   99,   76,   97,  101,
      130,  104,  131,  102,   88,  100,  103,  106,   57,  115,
       57,   57,   88,   88,   61,   88,   88,   88,  116,  116,
      116,  129,   88,   75,   75,   75,   79,   79,   79,   79,
       79,   88,  150,  132,   88,  139,   88,   88,  142,  151,
      135,  113,  133,  134,  113,   88,  136,   88,  117,   88,
      137,  118,   77,  119,   88,   80,   88,  120,  143,   78,

      145,  140,   81,  141,  155,   88,  138,  153,   88,  116,
      116,  116,  157,  152,  157,  154,   88,   88,   88,   88,
       88,   88,  156,   88,  152,   88,   88,   88,   88,  157,
       88,  157,   88,   88,   88,  161,   88,  165,   88,  159,
       88,   88,  160,  158,  164,  173,   88,  172,  171,  162,
      163,  166,   88,  176,   88,  178,  177,  157,  174,  157,
      175,   88,   88,  182,   88,  179,  185,   88,   88,  180,
      183,   88,   88,   88,   88,   88,   88,   88,  186,  188,
       88,  197,  184,  194,  192,  187,   88,   88,   88,   88,
      193,  195,  196,  189,   88,  190,   88,   88,  169,  181,

       88,   88,  191,   88,   88,  152,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   87,   87,
       87,   87,   87,   87,  107,  170,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  109,  169,  109,  168,  109,
      109,  109,  109,  109,  109,  109,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  114,  114,  167,
      125,  123,  114,  114,  121,  148,  121,  121,  121,  121,

      121,  121,  121,  121,  121,  122,  147,  122,  149,  146,
      149,  149,  144,  149,   88,   88,  128,  127,  126,  125,
      124,  123,  115,  198,  108,   89,   88,   84,   67,   66,
       62,   58,  198,   49,    7,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198

    } ;

static const flex_int16_t yy_chk[501] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    6,   12,
        5,    6,    9,   14,    9,    9,   19,    3,    4,   21,
       24,   24,   24,   24,   24,   27,   27,   22,   35,   19,
       21,   14,   22,    5,    6,    5,    6,   12,   23,   23,

       23,   22,   29,   29,   34,   36,   38,   37,   40,   24,
       23,   52,   39,   46,   35,   41,   24,   92,   42,   54,
       43,   44,   54,   91,   38,   40,   59,   23,   52,   36,
       34,   38,   34,   37,   23,   90,   41,   23,   39,   42,
       91,   44,   92,   42,   93,   41,   43,   46,   57,   66,
       57,   57,   94,   96,   59,   97,   98,  103,   66,   66,
       66,   90,  100,   75,   75,   75,   79,   79,   79,   79,
       79,   99,  122,   93,  102,  100,  101,  104,  103,  122,
       97,  113,   94,   96,  113,  131,   98,  132,   66,  129,
       99,   66,   75,   66,  130,   79,  133,   66,  104,   75,

      116,  101,   79,  102,  132,  135,   99,  130,  136,  116,
      116,  116,  134,  129,  134,  131,  134,  137,  138,  139,
      140,  142,  133,  141,  135,  153,  154,  143,  158,  157,
      161,  157,  159,  157,  162,  138,  160,  142,  172,  136,
      173,  175,  137,  134,  141,  157,  164,  154,  153,  139,
      140,  143,  166,  160,  174,  162,  161,  163,  158,  163,
      159,  163,  176,  172,  178,  164,  175,  177,  179,  166,
      173,  182,  184,  189,  191,  192,  193,  196,  176,  178,
      195,  194,  174,  190,  184,  177,  188,  187,  186,  185,
      189,  191,  193,  179,  183,  181,  180,  171,  170,  167,

      165,  156,  182,  155,  152,  192,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  203,  203,
      203,  203,  203,  203,  204,  151,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  205,  150,  205,  149,  205,
      205,  205,  205,  205,  205,  205,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  207,  207,  144,
      126,  124,  207,  207,  208,  119,  208,  208,  208,  208,

      208,  208,  208,  208,  208,  209,  118,  209,  210,  117,
      210,  210,  108,  210,   95,   87,   86,   82,   81,   80,
       78,   77,   65,   61,   49,   33,   30,   28,   18,   15,
       13,   11,    7,    2,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "babyc_lex.l"
#line 5 "babyc_lex.l"

/* ----------------------------------------------------------------
 * 
 * BabyC Toy compiler for educational purposes
 * 
 * ---------------------------------------------------------------- */

#include "bb_type.h"
#include "bb.tab.h"
#include "log_error.h"
#include "ast_annotate.h"

static char **raw_symbol_table = NULL;
static int raw_symbol_size = 0;

static char *symbol(char *s)
{
   for (int i = 0; i < raw_symbol_size; i++)
   { 
      if (!strcmp(s, raw_symbol_table[i]))
      {
         return raw_symbol_table[i];
      }
   }
   raw_symbol_table = realloc(raw_symbol_table, ++raw_symbol_size * sizeof (char *));
   return (raw_symbol_table[raw_symbol_size - 1] = strdup(s));
}

static char *number(char *n, int radix)
{
    AstInteger s;
    char str[100];
    
    ast_integer_set_str(&s, n, radix);
    return symbol(ast_integer_get_str(&s, str, 100));
}

static char *char_escape(char *n, int radix)
{
    char temp[10];
    unsigned long v = 0;
    
    if (radix == 8)
    {
        v = strtoul(n+2, NULL, 8);
    }
    else if (radix == 16)
    {
        v = strtoull(n+3, NULL, 16);
    }
    else
    {
        v = (unsigned char)n[1];
    }
    sprintf(temp, "%lu", v);
    return symbol(temp);    
}

static int line_number = 1;

#define LVAL(s) do { bblval.line = line_number; if (s) bblval.symbol = s; } while (0)

#line 945 "babyc_lex.flex.c"
#define YY_NO_INPUT 1

#line 948 "babyc_lex.flex.c"

#define INITIAL 0
#define comment 1
#define include 2

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 78 "babyc_lex.l"


#line 1168 "babyc_lex.flex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 199 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 435 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 80 "babyc_lex.l"
{ BEGIN(include); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "babyc_lex.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 82 "babyc_lex.l"
{ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 83 "babyc_lex.l"
{ BEGIN(0); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "babyc_lex.l"
{ /* Discard preprocessor comments. */ }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 87 "babyc_lex.l"
{ LVAL(0); bblval.symbol = symbol(yytext); return T_STRING; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 89 "babyc_lex.l"
{ /* Discard comment */ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 91 "babyc_lex.l"
{ BEGIN(comment); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "babyc_lex.l"
{ /* eat comment */ }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 94 "babyc_lex.l"
{ ++line_number; /* eat comment */ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 95 "babyc_lex.l"
{ /* eat comment */ }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 96 "babyc_lex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "babyc_lex.l"
{ /* Ignore whitespace */ }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 99 "babyc_lex.l"
{ ++line_number; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 101 "babyc_lex.l"
{ LVAL(0); return T_PLUS_EQ; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 102 "babyc_lex.l"
{ LVAL(0); return T_MINUS_EQ; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "babyc_lex.l"
{ LVAL(0); return T_MUL_EQ; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "babyc_lex.l"
{ LVAL(0); return T_DIV_EQ; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 105 "babyc_lex.l"
{ LVAL(0); return T_MOD_EQ; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 106 "babyc_lex.l"
{ LVAL(0); return T_OR_EQ; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 107 "babyc_lex.l"
{ LVAL(0); return T_AND_EQ; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 108 "babyc_lex.l"
{ LVAL(0); return T_XOR_EQ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 109 "babyc_lex.l"
{ LVAL(0); return T_RSHIFT_EQ; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "babyc_lex.l"
{ LVAL(0); return T_LSHIFT_EQ; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 112 "babyc_lex.l"
{ LVAL(0); return T_INCREMENT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 113 "babyc_lex.l"
{ LVAL(0); return T_DECREMENT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 114 "babyc_lex.l"
{ LVAL(0); return T_LOGICAL_OR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 115 "babyc_lex.l"
{ LVAL(0); return T_LOGICAL_AND; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 116 "babyc_lex.l"
{ LVAL(0); return T_RSHIFT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 117 "babyc_lex.l"
{ LVAL(0); return T_LSHIFT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 118 "babyc_lex.l"
{ LVAL(0); return T_LARGER_OR_EQUAL; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 119 "babyc_lex.l"
{ LVAL(0); return T_LESS_OR_EQUAL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 120 "babyc_lex.l"
{ LVAL(0); return T_EQUAL; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 121 "babyc_lex.l"
{ LVAL(0); return T_NEQUAL; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 123 "babyc_lex.l"
{ LVAL(0); return T_OPEN_BRACE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 124 "babyc_lex.l"
{ LVAL(0); return T_CLOSE_BRACE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 125 "babyc_lex.l"
{ LVAL(0); return '('; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 126 "babyc_lex.l"
{ LVAL(0); return ')'; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 127 "babyc_lex.l"
{ LVAL(0); return '['; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 128 "babyc_lex.l"
{ LVAL(0); return ']'; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 129 "babyc_lex.l"
{ LVAL(0); return '~'; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 130 "babyc_lex.l"
{ LVAL(0); return '!'; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 131 "babyc_lex.l"
{ LVAL(0); return '+'; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 132 "babyc_lex.l"
{ LVAL(0); return '-'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 133 "babyc_lex.l"
{ LVAL(0); return '*'; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 134 "babyc_lex.l"
{ LVAL(0); return '/'; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 135 "babyc_lex.l"
{ LVAL(0); return '%'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 136 "babyc_lex.l"
{ LVAL(0); return '|'; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 137 "babyc_lex.l"
{ LVAL(0); return '&'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 138 "babyc_lex.l"
{ LVAL(0); return '^'; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 139 "babyc_lex.l"
{ LVAL(0); return '<'; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 140 "babyc_lex.l"
{ LVAL(0); return '>'; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 141 "babyc_lex.l"
{ LVAL(0); return '='; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 142 "babyc_lex.l"
{ LVAL(0); return ';'; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 143 "babyc_lex.l"
{ LVAL(0); return ','; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 144 "babyc_lex.l"
{ LVAL(0); return ':'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 146 "babyc_lex.l"
{
                LVAL(0); bblval.symbol = number(yytext, 10); return T_NUMBER;
              }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 150 "babyc_lex.l"
{
                LVAL(0); bblval.symbol = number(&yytext[2], 16); return T_NUMBER;
              }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 154 "babyc_lex.l"
{
                LVAL(0); bblval.symbol = number(yytext, 8); return T_NUMBER;
              }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 158 "babyc_lex.l"
{
                LVAL(0); bblval.symbol = char_escape(yytext, 16); return T_NUMBER;
              }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 161 "babyc_lex.l"
{
                LVAL(0); bblval.symbol = char_escape(yytext, 8); return T_NUMBER;
              }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 164 "babyc_lex.l"
{
                LVAL(0); bblval.symbol = char_escape(yytext, 0); return T_NUMBER;
              }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 167 "babyc_lex.l"
{
                LVAL(0); bblval.symbol = symbol("12"); return T_NUMBER;
              }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 170 "babyc_lex.l"
{
                LVAL(0); bblval.symbol = symbol("13"); return T_NUMBER;
              }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 173 "babyc_lex.l"
{
                LVAL(0); bblval.symbol = symbol("8"); return T_NUMBER;
              }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 177 "babyc_lex.l"
{ LVAL(0); return T_IF; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 178 "babyc_lex.l"
{ LVAL(0); return T_ELSE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 179 "babyc_lex.l"
{ LVAL(0); return T_GOTO; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 180 "babyc_lex.l"
{ LVAL(0); return T_WHILE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 181 "babyc_lex.l"
{ LVAL(0); return T_BREAK; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 182 "babyc_lex.l"
{ LVAL(0); return T_CONTINUE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 183 "babyc_lex.l"
{ LVAL(0); return T_SIZEOF; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 184 "babyc_lex.l"
{ LVAL(0); return T_RETURN; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 185 "babyc_lex.l"
{ LVAL(0); return T_STATIC; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 186 "babyc_lex.l"
{ LVAL(0); return T_VOID; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 187 "babyc_lex.l"
{ LVAL(0); return T_UNSIGNED; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 188 "babyc_lex.l"
{ LVAL(0); return T_SIGNED; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 189 "babyc_lex.l"
{ LVAL(0); bblval.symbol = symbol(yytext); return T_TYPE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 190 "babyc_lex.l"
{ LVAL(0); bblval.symbol = symbol(yytext); return T_TYPE; }
	YY_BREAK
case 80:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 191 "babyc_lex.l"
{ LVAL(0); bblval.symbol = symbol(yytext); return T_LABEL; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 192 "babyc_lex.l"
{ LVAL(0); bblval.symbol = symbol(yytext); return T_IDENTIFIER; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 194 "babyc_lex.l"
{ unsigned char c = *yytext;  log_error("unknown byte 0x%02x line %d", (unsigned)c, line_number); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 196 "babyc_lex.l"
ECHO;
	YY_BREAK
#line 1665 "babyc_lex.flex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(include):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 199 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 199 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 198);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 196 "babyc_lex.l"



